@startuml

class App{
    Main()
    readUserInput()
    matchFound()
    iterativeLoop()
}

class JSON{
    convertJsonToArray()
}

class Product{
    + String name;
    + double price;
    + int quantity;
}
App <-- Product
Product <-- JSON

@enduml