@startuml
'https://plantuml.com/class-diagram

class FileOperations {
    List getListOfNames();
}

class StringAlpha{
    List sortStringAlphabetically();
    printListToFile();
}

class ex41 {
    main();

}

FileOperations --> ex41
StringAlpha --> ex41
@enduml